language: php
php:
  - 5.4
install:
  #- sudo apt-get install -q virtualbox --fix-missing # Everything falls apart here exactly.
  #- sudo wget -nv http://files.vagrantup.com/packages/7e400d00a3c5a0fdf2809c8b5001a035415a607b/vagrant_1.2.2_x86_64.deb
  #- sudo dpkg -i vagrant_1.2.2_x86_64.deb
  #- sudo vagrant plugin install vagrant-plugin-bundler
script: 
# - cd vagrant
#- sudo vagrant up # The error is only presented when executing vagrant up
#- cd ../
  - php codecept.phar run --html --steps -g dev
after_script:
#- sudo vagrant halt
#- sudo vagrant destroy